### ISSUE TITLE
Утечка токена ВКонтакте

### ISSUE THREAD

**Issue by kiriharu** [Beloslav13/progs_and_code#1]
У меня есть ощущение, что вы начали совсем недавно пользоваться github, поэтому вставлю свои пять копеек.

В файле [vk_parser/vk.py](https://github.com/Beloslav13/progs_and_code/blob/master/vk_parser/vk.py) предположительно есть токен от вашего аккаунта ВКонтакте или от вашего приложения. Это в корне неправильно и просто небезопасно, поэтому пожалуйста - уберите его и поменяйте пароль.

**Comment by Beloslav13** [comment]
Спасибо, убрал.
